### ISSUE TITLE
Communication protocol with Spectrometer?

### ISSUE THREAD

**Issue by astuder** [g3gg0/SpectrumPlotter#1]
I came across SpectrumPlotter via the recent article on Hackaday. I like the functionality of your GUI application and would like to use it with my own spectrometer project (https://github.com/astuder/epc901).

My first goal would be to adapt my firmware to present itself in a way that's compatible with SpectrumPlotter as is.

Do you have information about the serial protocol that your application expects?

**Comment by g3gg0** [comment]
Hi,

the protocol is based on the original firmware here: https://tcd1304.wordpress.com/the-firmware/
All the SH/ICG terms and timings are explained there.

After sending 0x45, 0x52, 0x00, 0x00, 0x00, 0x00, 0xFF, 0x00, 0x01, 0x00, 0x02, 0x00 you will receive 10 ascii characters "[g3gg0.de]"
This is only issued once to detect my custom firmware as the original firmware misses the trigger feature.


Then configure capture mode using 0x45, 0x52, DD, DD, DD, DD, TT, 0x00, 0x01, 0x00, 0x02, 0x00 
where DD is the trigger delay 32 bit LE and TT is 0x00 for continuous mode and 0x02 when to wait for the trigger signal.

Finally send 0x45, 0x52, SS, SS, SS, SS, II, II, II, II, 0x00, 0x00 where SS is the SH period and II is the ICG period
Either instantly or when the trigger was detected, you will receive 3694 16 bit LE values and you can start over.
Very hardcoded to that specific setup, but didn't want to change the whole serial protocol just for adding a trigger.

**Comment by astuder** [comment]
Thank you for the detailed response. I think this should get me started.
